from .client import AsyncMailGlyph, MailGlyph
from .exceptions import (
    ApiError,
    AuthenticationError,
    MailGlyphError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)
from .models import (
    BulkEmailValidationJob,
    BulkEmailValidationJobsPage,
    Campaign,
    Contact,
    DeleteBulkEmailValidationResult,
    FilterCondition,
    FilterGroup,
    Segment,
    SegmentFilter,
    SendCampaignResult,
    SendEmailResult,
    StaticSegmentMembersAddResult,
    StaticSegmentMembersRemoveResult,
    Template,
    TrackEventResult,
    VerificationCreditLedgerEntry,
    VerificationCreditLedgerPage,
    VerificationCreditSummary,
    VerifyEmailResult,
)

__version__ = "2.2.0"

__all__ = [
    "ApiError",
    "AsyncMailGlyph",
    "AuthenticationError",
    "BulkEmailValidationJob",
    "BulkEmailValidationJobsPage",
    "Campaign",
    "Contact",
    "DeleteBulkEmailValidationResult",
    "FilterCondition",
    "FilterGroup",
    "MailGlyph",
    "MailGlyphError",
    "NotFoundError",
    "RateLimitError",
    "SendCampaignResult",
    "Segment",
    "SegmentFilter",
    "SendEmailResult",
    "StaticSegmentMembersAddResult",
    "StaticSegmentMembersRemoveResult",
    "Template",
    "TrackEventResult",
    "ValidationError",
    "VerificationCreditLedgerEntry",
    "VerificationCreditLedgerPage",
    "VerificationCreditSummary",
    "VerifyEmailResult",
    "__version__",
]
